platform :ios, '10.0'
use_frameworks!

ENV['COCOAPODS_DISABLE_STATS'] = "true" ## This disabled the Sending Stats when running Pod install in terminal

target 'PopupDialog_Example' do

  pod 'PopupDialog', :path => '../'
  pod 'SwiftLint', '~> 0.34.0'

  target 'PopupDialog_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 8.0.2'
    pod 'iOSSnapshotTestCase', '~> 6.1.0'

  end
end
