use_frameworks!

target 'PopupDialog_Example' do
  pod 'PopupDialog', :path => '../'

  target 'PopupDialog_Tests' do
    inherit! :search_paths    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "2.3"
    end
  end
end
