use_frameworks!

target 'PopupDialog_Example' do
  pod 'PopupDialog', :path => '../'

  target 'PopupDialog_Tests' do
    inherit! :search_paths
    pod 'Nimble', '~> 5.0.0'
    pod 'FBSnapshotTestCase'
  end
end
