language: objective-c
osx_image: xcode10.2
env:
  global:
    - WORKSPACE=Example/PopupDialog.xcworkspace
    - IOS_FRAMEWORK_SCHEME="PopupDialog-Example"
    - IOS_SDK=iphonesimulator12.2
  matrix:
    - DESTINATION="OS=12.2,name=iPhone Xʀ"  SIMNAME="com.apple.CoreSimulator.SimDeviceType.iPhone-Xʀ, 12.2"  SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK" POD_LINT="YES"
    - DESTINATION="OS=10.2,name=iPhone 6"   SIMNAME="com.apple.CoreSimulator.SimDeviceType.iPhone-6, 10.2"   SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK" POD_LINT="NO"
    - DESTINATION="OS=11.1,name=iPad Air 2" SIMNAME="com.apple.CoreSimulator.SimDeviceType.iPad-Air-2, 11.1" SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK" POD_LINT="NO"
before_install:
  - npm install ios-sim -g
  - gem install cocoapods --no-document --quiet
  - pod install --project-directory=./Example --repo-update
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcrun simctl list

  # "Prewarm" simulators as of https://github.com/travis-ci/travis-ci/issues/6675
  # - ios-sim start --devicetypeid "$SIMNAME"

  # Build Framework in Debug and run tests
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
